version: '3.8'

services:
  gate_module:
    env_file:
      - "../.env"
    build:
      context: .
    container_name: gate_module
    restart: always
    ports:
      - "8080:8080"
    environment:
      MODULE_GROUP_ID: GATE_GROUP_ID
#    deploy:
#      mode: replicated
#      replicas: 2

